# Generated by Django 3.2.20 on 2023-08-24 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
        ('posts', '0001_initial'),
        ('comments', '0003_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='discussions.discussion'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.post'),
        ),
    ]
